### ISSUE TITLE
Question about store extensions

### ISSUE THREAD

**Issue by sebestyn168** [addok/addocker#4]
Hi,

I'm not familiar with redis and i'm trying to integrate addok-psql-store extension in order to avoid using it.

But it seems store extensions only allow to split off the weight of the the DB, not to completly bypass redis. Is that right ?

I'm also wondering which extension I should use between sqlite and psql. Could you point out any information about their memory/performance strengths and weaknesses ?

**Comment by yohanboniface** [comment]
> But it seems store extensions only allow to split off the weight of the the DB, not to completly bypass redis. Is that right 

Yes, store plugins are *only* for storing the documents, not the indexes, which are in Redis. Redis is the Addok engine, so there is not way bypassing it.

> I'm also wondering which extension I should use between sqlite and psql.

Use sqlite unless you have billions of documents (and if you have only some thousands of documents, you may just keep Redis as your storage).

**Comment by sebestyn168** [comment]
Thank you
